"""
Entry point for the application. Triggers the training pipeline.
Inputs: None
Outputs: Model artifacts generated by the pipeline.
"""
from src.pipline.training_pipeline import TrainPipeline

pipeline = TrainPipeline()
pipeline.run_pipeline()